<a href="https://colab.research.google.com/github/tartam1/IT545/blob/main/Lab_2_Assignment_WI24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab Assignment 2

## Chapter 3 - Built-in Data Structures, Functions, and Files
## Chapter 4 - NumPy Basics: Arrays and Vectorized Computation

In [1]:
# Import Series and DataFrame into local namespace
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## Problem 1

#### In this problem, please type out the code (in separate cells) under the Tuple heading (stop before List heading) in Section 3.1 Data Structures and Sequences (chapter 3 of textbook).

In [ ]:
# Type code below

In [2]:
# Exploring the Tuple data structure in Python
tup = 4, 5, 6
tup

(4, 5, 6)

In [3]:
# No parentheses option
tup = (4, 5, 6)
tup

(4, 5, 6)

In [5]:
# Convert to a tuple
tuple([4, 0, 2])

(4, 0, 2)

In [6]:
tup = tuple('string')
tup

('s', 't', 'r', 'i', 'n', 'g')

In [9]:
# Accessing a specific element
tup[0]

's'

In [12]:
# Sometimes parentheses are needed
nested_tup = (4, 5, 6), (7, 8)
nested_tup

((4, 5, 6), (7, 8))

In [13]:
nested_tup[0]

(4, 5, 6)

In [14]:
nested_tup[1]

(7, 8)

In [15]:
# Cannot modify after
tup = tuple(['foo', [1, 2], True])
tup[2] = False

TypeError: 'tuple' object does not support item assignment

In [16]:
# if mutable object inside tuple can be modified
tup[1].append(3)
tup

('foo', [1, 2, 3], True)

In [17]:
# Concatenate tuples
(4, None, 'foo') + (6, 0) + ('bar',)

(4, None, 'foo', 6, 0, 'bar')

In [18]:
# Multiply Tuples
('foo', 'bar') * 4

('foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'bar')

In [19]:
# uplacking tuples
tup = (4, 5, 6)
a, b, c = tup
b

5

In [20]:
# sequences with nested tuples
tup = 4, 5, (6, 7)
a, b, (c, d) = tup
d

7

In [21]:
# swap names
a, b = 1, 2
a

1

In [22]:
b

2

In [23]:
b, a = a, b
a

2

In [24]:
b

1

In [25]:
# tuple unpacking usasge with lists and tuples
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
for a, b, c in seq:
    print(f'a={a}, b={b}, c={c}')

a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


In [27]:
# returning from a function
values = 1, 2, 3, 4, 5
a, b, *rest = values
a

1

In [28]:
b

2

In [29]:
rest

[3, 4, 5]

In [30]:
a, b, *_ = values

In [31]:
# tuple methods
a = (1, 2, 2, 2, 3, 4, 2)
a.count(2)

4

## Problem 2

#### In this problem, please type out the code (in separate cells) under the List heading (stop before  Dictionary heading) in Section 3.1 Data Structures and Sequences (chapter 3 of textbook).

In [33]:
# Type code below
# lists
a_list = [2, 3, 7, None]
tup = ('foo', 'bar', 'baz')
b_list = list(tup)
b_list


['foo', 'bar', 'baz']

In [34]:
b_list[1] = 'peekaboo'
b_list

['foo', 'peekaboo', 'baz']

In [35]:
b_list

['foo', 'peekaboo', 'baz']

In [36]:
# built in list funcition
gen = range(10)
gen

range(0, 10)

In [37]:
list(gen)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
# adding and removing elements
b_list.append('dwarf')
b_list

['foo', 'peekaboo', 'baz', 'dwarf']

In [39]:
# using insert, note insert is more expensive that append
b_list.insert(1, 'red')
b_list

['foo', 'red', 'peekaboo', 'baz', 'dwarf']

In [40]:
b_list.pop(2)
b_list

['foo', 'red', 'baz', 'dwarf']

In [41]:
# removing
b_list.append('foo')
b_list

['foo', 'red', 'baz', 'dwarf', 'foo']

In [42]:
b_list.remove('foo')
b_list

['red', 'baz', 'dwarf', 'foo']

In [43]:
# Checking if item in list
"dwarf" in b_list

True

In [44]:
# Concatenating and combining lists
[4, None, "foo"] + [7, 8, (2, 3)]

[4, None, 'foo', 7, 8, (2, 3)]

In [45]:
# multiple elements
x = [4, None, "foo"]
x.extend([7, 8, (2, 3)])
x

[4, None, 'foo', 7, 8, (2, 3)]

In [47]:
# sorting
a = [7, 2, 5, 1, 3]
a.sort()
a

[1, 2, 3, 5, 7]

In [48]:
# more sort options
b = ["saw", "small", "He", "foxes", "six"]
b.sort(key=len)
b

['He', 'saw', 'six', 'small', 'foxes']

In [59]:
# slicing
seq = [7, 2, 3, 7, 5, 6, 0, 1]
seq[1:5]

[2, 3, 7, 5]

In [60]:
# seq slice
seq[3:5] = [6, 3]
seq

[7, 2, 3, 6, 3, 6, 0, 1]

In [61]:
# start and stop omitted
seq[:5]

[7, 2, 3, 6, 3]

In [62]:
seq[3:]

[6, 3, 6, 0, 1]

In [63]:
# negative slices are from the end
seq[-4:]

[3, 6, 0, 1]

In [64]:
seq[-6:-2]

[3, 6, 3, 6]

In [65]:
# step example
seq[::2]

[7, 3, 3, 0]

In [66]:
seq[::-1]

[1, 0, 6, 3, 6, 3, 2, 7]

## Problem 3

#### In this problem, please type out the code (in separate cells) under the Dictionary heading (stop before  Set heading) in Section 3.1 Data Structures and Sequences (chapter 3 of textbook).

In [68]:
# Type code below
# Dictionaries
empty_dict = {}
d1 = {"a": "some value", "b": [1, 2, 3, 4]}
d1


{'a': 'some value', 'b': [1, 2, 3, 4]}

In [69]:
# accessing elements
d1[7] = "an integer"
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [70]:
d1["b"]

[1, 2, 3, 4]

In [71]:
# check if a key is in dic
"b" in d1

True

In [72]:
# delete and pop
d1[5] = "some value"
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer', 5: 'some value'}

In [73]:
d1["dummy"] = "another value"
d1

{'a': 'some value',
 'b': [1, 2, 3, 4],
 7: 'an integer',
 5: 'some value',
 'dummy': 'another value'}

In [74]:
del d1[5]
d1

{'a': 'some value',
 'b': [1, 2, 3, 4],
 7: 'an integer',
 'dummy': 'another value'}

In [75]:
ret = d1.pop("dummy")
ret

'another value'

In [76]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [77]:
# keys and values
list(d1.keys())

['a', 'b', 7]

In [78]:
list(d1.values())

['some value', [1, 2, 3, 4], 'an integer']

In [80]:
list(d1.items())

[('a', 'some value'), ('b', [1, 2, 3, 4]), (7, 'an integer')]

In [81]:
d1.update({"b": "foo", "c": 12})
d1

{'a': 'some value', 'b': 'foo', 7: 'an integer', 'c': 12}

In [83]:
# dics from swquences
tuples = zip(range(5), reversed(range(5)))
tuples

In [84]:
mapping = dict(tuples)
mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

In [85]:
# default values
words = ["apple", "bat", "bar", "atom", "book"]
by_letter = {}
for word in words:
    letter = word[0]
    if letter not in by_letter:
        by_letter[letter] = [word]
    else:
        by_letter[letter].append(word)
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

In [86]:
# set default to simplify the previous flow
by_letter = {}
for word in words:
    letter = word[0]
    by_letter.setdefault(letter, []).append(word)
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

In [88]:
# collections module
from collections import defaultdict
by_letter = defaultdict(list)
for word in words:
    by_letter[word[0]].append(word)

In [89]:
hash("string")

-89675592086974503

In [90]:
hash((1, 2, (2, 3)))

-9209053662355515447

In [91]:
hash((1, 2, [2, 3]))

TypeError: unhashable type: 'list'

In [93]:
d = {}

In [94]:
d[tuple([1, 2, 3])] = 5
d

{(1, 2, 3): 5}

## Problem 4

#### In this problem, please type out the code (in separate cells) under the Set heading (stop before 3.2 Functions) in Section 3.1 Data Structures and Sequences (chapter 3 of textbook).

In [95]:
# Type code below
# Sets
set([2, 2, 2, 1, 3, 3])

{1, 2, 3}

In [96]:
{2, 2, 2, 1, 3, 3}

{1, 2, 3}

In [97]:
# set operations different ways
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}

In [98]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8}

In [99]:
a | b

{1, 2, 3, 4, 5, 6, 7, 8}

In [100]:
a.intersection(b)

{3, 4, 5}

In [101]:
a & b

{3, 4, 5}

In [102]:
c = a.copy()
c |= b
c

{1, 2, 3, 4, 5, 6, 7, 8}

In [103]:
d = a.copy()
d &= b
d

{3, 4, 5}

In [104]:
# elememts must be immutable and hashable
my_data = [1, 2, 3, 4]
my_set = {tuple(my_data)}
my_set

{(1, 2, 3, 4)}

In [105]:
# Checking subsets and or supersets
a_set = {1, 2, 3, 4, 5}
{1, 2, 3}.issubset(a_set)

True

In [106]:
a_set.issuperset({1, 2, 3})

True

Not sure if supposed to do Built-In Sequence Functions but I will anyways. Good to see.

In [107]:
# sorted
sorted([7, 1, 2, 6, 0, 3, 2])

[0, 1, 2, 2, 3, 6, 7]

In [108]:
sorted("horse race")

[' ', 'a', 'c', 'e', 'e', 'h', 'o', 'r', 'r', 's']

In [109]:
# zip
seq1 = ["foo", "bar", "baz"]
seq2 = ["one", "two", "three"]
zipped = zip(seq1, seq2)
list(zipped)

[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]

In [110]:
seq3 = [False, True]
list(zip(seq1, seq2, seq3))

[('foo', 'one', False), ('bar', 'two', True)]

In [111]:
for index, (a, b) in enumerate(zip(seq1, seq2)):
    print(f"{index}: {a}, {b}")

0: foo, one
1: bar, two
2: baz, three


In [113]:
# reversed
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [114]:
# list set and dic comprehensions
strings = ["a", "as", "bat", "car", "dove", "python"]

In [115]:
[x.upper() for x in strings if len(x) > 2]

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [116]:
unique_lengths = {len(x) for x in strings}

In [117]:
unique_lengths

{1, 2, 3, 4, 6}

In [118]:
# map
set(map(len, strings))

{1, 2, 3, 4, 6}

In [119]:
loc_mapping = {val: index for index, val in enumerate(strings)}
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

In [120]:
# nested list comprehensions
all_data = [["John", "Emily", "Michael", "Mary", "Steven"],
            ["Maria", "Juan", "Javier", "Natalia", "Pilar"]]

In [122]:
names_of_interest = []
for names in all_data:
    enough_es = [name for name in names if name.count("a") >= 2]
    names_of_interest.extend(enough_es)

In [123]:
names_of_interest

['Maria', 'Natalia']

In [124]:
# making it more concise
result = [name for names in all_data for name in names
          if name.count("a") >= 2]

In [125]:
result

['Maria', 'Natalia']

In [126]:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
flattened = [x for tup in some_tuples for x in tup]
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [127]:
[[x for x in tup] for tup in some_tuples]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## Problem 5

#### In this problem, please type out the code (in separate cells) under the 3.2 Functions heading (stop before Generators heading) in Section 3.2 Functions (chapter 3 of textbook).

In [128]:
# Type code below
# Functions and output and assignment
def my_function(x, y):
    return x + y

In [129]:
my_function(1, 2)

3

In [130]:
result = my_function(1, 2)
result

3

In [131]:
def function_without_return(x):
    print(x)

In [132]:
result = function_without_return("hello!")

hello!


In [133]:
print(result)

None


In [134]:
def my_function2(x, y, z=1.5):
    if z > 1:
        return z * (x + y)
    else:
        return z / (x + y)

In [135]:
my_function2(5, 6, z=0.7)

0.06363636363636363

In [136]:
my_function2(3.14, 7, 3.5)

35.49

In [137]:
my_function2(10, 20)

45.0

In [138]:
# Namespaces, scope, and local functions
def func():
    a = []
    for i in range(5):
        a.append(i)

In [139]:
a = []
def func():
    for i in range(5):
        a.append(i)

In [140]:
func()
a

[0, 1, 2, 3, 4]

In [141]:
func()
a

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [142]:
# globan and nonlocal keywords
a = None
def bind_a_variable():
    global a
    a = []
bind_a_variable()
print(a)

[]


In [143]:
# returen multiple values
# Just wanted to see this and how it worked
def f():
    a = 5
    b = 6
    c = 7
    return a, b, c

a, b, c = f()

In [144]:
return_value = f()

In [145]:
print(return_value)

(5, 6, 7)


In [146]:
# functions are objects
states = ["   Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda",
          "south   carolina##", "West virginia?"]

In [147]:
import re
def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub("[!#?]", "", value)
        value = value.title()
        result.append(value)
    return result

In [148]:
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [149]:
# another way
def remove_punctuation(value):
    return re.sub("[!#?]", "", value)

clean_ops = [str.strip, remove_punctuation, str.title]
def clean_strings(strings, ops):
    result = []
    for value in strings:
        for function in clean_ops:
            value = function(value)
        result.append(value)
    return result

In [150]:
clean_strings(states, clean_ops)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [151]:
# functional pattern
for x in map(remove_punctuation, states):
    print(x)

   Alabama 
Georgia
Georgia
georgia
FlOrIda
south   carolina
West virginia


In [152]:
# lamba functions
def short_function(x):
    return x * 2

equiv_anon = lambda x: x * 2

In [153]:
def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

ints = [4, 0, 1, 5, 6]
apply_to_list(ints, lambda x: x * 2)

[8, 0, 2, 10, 12]

In [154]:
strings = ["foo", "card", "bar", "aaaa", "abab"]

In [155]:
strings.sort(key=lambda x: len(set(x)))
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

## Problem 6

#### In this problem, please type out the code (in separate cells) under the Generatorss heading (stop before Errors and Exception Handling heading) in Section 3.2 Functions (chapter 3 of textbook).

In [156]:
# Type code below
# generators to make iteraable
some_dict = {"a": 1, "b": 2, "c": 3}
for key in some_dict:
    print(key)

a
b
c


In [157]:
dict_iterator = iter(some_dict)
dict_iterator

In [158]:
list(dict_iterator)

['a', 'b', 'c']

In [159]:
# more generator
def squares(n=10):
    print(f"Generating squares from 1 to {n ** 2}")
    for i in range(1, n + 1):
        yield i ** 2

In [160]:
gen = squares()
gen

<generator object squares at 0x7cf152e79700>

In [161]:
# before was the set up now is the work
for x in gen:
    print(x, end=" ")

Generating squares from 1 to 100
1 4 9 16 25 36 49 64 81 100 

In [162]:
# generator expressions this is a short had for a longer function for loop
gen = (x ** 2 for x in range(100))
gen

<generator object <genexpr> at 0x7cf153ae3ed0>

In [163]:
# generator instead of list comprehensions
sum(x ** 2 for x in range(100))

328350

In [164]:
dict((i, i ** 2) for i in range(5))

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [166]:
# itertools module
import itertools
def first_letter(x):
    return x[0]
names = ["Alan", "Adam", "Wes", "Will", "Albert", "Steven"]
for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names))

A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']


In [167]:
# errors and exception handling
# Started it before reviewing to question to see it is not required. but it was fun. :)
float("1.2345")

1.2345

In [168]:
float("something")

ValueError: could not convert string to float: 'something'

In [169]:
# set up function with try except
def attempt_float(x):
    try:
        return float(x)
    except:
        return x

In [170]:
attempt_float("1.2345")

1.2345

In [171]:
attempt_float("something")

'something'

In [172]:
# float error
float((1, 2))

TypeError: float() argument must be a string or a real number, not 'tuple'

In [173]:
# suppress error
def attempt_float(x):
    try:
        return float(x)
    except ValueError:
        return x

In [174]:
attempt_float((1, 2))

TypeError: float() argument must be a string or a real number, not 'tuple'

In [175]:
# try to catch multiple exception types
def attempt_float(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return x

In [176]:
# just trying not in book
attempt_float((1, 2))

(1, 2)

In [ ]:
# didn't do the file open since partial code

## Problem 7 & 8 (worth 4 points)

#### In this problem, please type out the code (in separate cells) under the 4.1 The NumPy ndarray: A Multidimensional Array Object heading (stop before 4.2 Pseudorandom Number Generation heading) in 4.1 The NumPy ndarray: A Multidimensional Array Object (chapter 4 of textbook).

In [4]:
# Type code below
# diving into NumPy ndarray
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# Get info about arr2
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

In [13]:
# check out dat types
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int64')

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
# not the same as in the book. I got the "gargage" values
np.empty((2, 3, 2))

array([[[2.43777081e-315, 0.00000000e+000],
        [2.10077583e-312, 6.79038654e-313],
        [2.22809558e-312, 2.14321575e-312]],

       [[2.35541533e-312, 6.79038654e-313],
        [2.22809558e-312, 2.14321575e-312],
        [2.46151512e-312, 2.41907520e-312]]])

In [18]:
# arange
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
# data types for ndarrays
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
# casting
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [22]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [23]:
float_arr.dtype

dtype('float64')

In [24]:
# more casting with truncation
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [25]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [33]:
# strings but throws an error since removed in 2.0 version of Numpy
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(float)

AttributeError: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.

In [34]:
int_array = np.arange(10)

In [35]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
zeros_unit32 = np.zeros(8, dtype="u4")
zeros_unit32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [37]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [39]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [41]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [42]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [44]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [47]:
# basic indexin and sliceing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# some slicing examples
# output a little differnt than book type is given here
arr[5]

np.int64(5)

In [51]:
arr[5:8]

array([5, 6, 7])

In [52]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [54]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [55]:
# mutations
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [57]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [58]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [59]:
arr2d[0][2]

np.int64(3)

In [60]:
arr2d[0, 2]

np.int64(3)

In [61]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
# scalar values and arrays
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr3d[1, 0]

array([7, 8, 9])

In [66]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [67]:
x[0]

array([7, 8, 9])

In [68]:
# indexing with slices learning the axis
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [69]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [70]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [74]:
lower_dim_slice = arr2d[1, :2]
lower_dim_slice.shape

(2,)

In [75]:
arr2d[:2, 2]

array([3, 6])

In [76]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [77]:
arr2d[:2, 1:] = 0

In [78]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [79]:
# Boolean Indexing
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [80]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

In [81]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [82]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [83]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [84]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [85]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [86]:
data[names == "Bob", 1]

array([7, 0])

In [87]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [88]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [89]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [90]:
cond = names == "Bob"

In [91]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [92]:
mask = (names == "Bob") | (names == "Will")


In [93]:
mask

array([ True, False,  True,  True,  True, False, False])

In [94]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [95]:
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [96]:
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [97]:
# Fancy Indexing
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [98]:
 arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [99]:
arr = np.arange(32).reshape((8, 4))

In [100]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [101]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [102]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [103]:
 arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [104]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0

In [105]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [106]:
# transposing arrays and swapping axes
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [107]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [108]:
# matrix computations
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1
]])

In [109]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [110]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [111]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [112]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [113]:
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

## Problem 9

#### In this problem, please type out the code (in separate cells) under the 4.2 Pseudorandom Number Generation and 4.3 Universal Functions: Fast Element-Wise Array Functions (stop before 4.4 Array-Oriented Programming with Arrays heading) in 4.2 Pseudorandom Number Generation and 4.3 Universal Functions: Fast Element-Wise Array Functions (chapter 4 of textbook).

In [ ]:
# Type code below

## Problem 10

#### In this problem, please type out the code (in separate cells) under the 4.4 Array-Oriented Programming wth Arrays, 4.5 File Input and Output with Arrays, 4.6 Linear Algebra (stop before 4.6 Example: Random Walks heading) in 4.2 Pseudorandom Number Generation and 4.3 Universal Functions: Fast Element-Wise Array Functions (chapter 4 of textbook).

In [ ]:
# Type code below